Feature/listing
f-lab-edu/FKREAM pull request #49
Opened 2023-04-23 07:45 UTC by bfinecpa

2023-04-25 20:11 UTC, f-lab-jason requested changes

2023-04-25 20:11 UTC, f-lab-jason commented on src/main/java/com/flab/fkream/listing/ListingController.java
> +public class ListingController {
세션에서 말씀드렸던것처럼 `/listing`으로 통일하고 파라미터로 타입을 받는 형식을 고려하면 좋겠어요!

2023-04-25 20:11 UTC, f-lab-jason commented on src/main/java/com/flab/fkream/listing/ListingService.java
> +public class ListingService {
1. 왜 sneakers 타입만 약간 다른 쿼리를 쓰는건가요?
2. '1개월 데이터 조회'가 기본적인 추천 로직이고 대부분 반복되는걸로 보이는데 이 부분을 mapper에서 기본값으로 처리할 수 있도록 리팩토링 하는건 어떨까요? overloading으로 파라미터가 있으면 그걸 쓰고 아니면 1개월을 보는 형태로요

2023-04-27 00:03 UTC, bfinecpa commented on src/main/java/com/flab/fkream/listing/ListingController.java
> +public class ListingController {
네 알겠습니다

2023-04-27 00:08 UTC, bfinecpa commented on src/main/java/com/flab/fkream/listing/ListingService.java
> +public class ListingService {
> 1. 왜 sneakers 타입만 약간 다른 쿼리를 쓰는건가요?
> 2. '1개월 데이터 조회'가 기본적인 추천 로직이고 대부분 반복되는걸로 보이는데 이 부분을 mapper에서 기본값으로 처리할 수 있도록 리팩토링 하는건 어떨까요? overloading으로 파라미터가 있으면 그걸 쓰고 아니면 1개월을 보는 형태로요

1. 기능 정의에 있어서 sneakers는 인기상승이라는 기능으로 정의했습니다. 여기서 인기 상승은 2달전 거래량 대비 1달전 거래량이 많이 상승한 것을 의미합니다.
2. 네. 변경하겠습니다.

2023-05-01 19:38 UTC, f-lab-jason approved these changes

2023-05-01 19:38 UTC, f-lab-jason commented on src/main/java/com/flab/fkream/listing/ListingCriteria.java
> +}
이거 formatter 돌려보시겠어요?

2023-05-12 01:19 UTC, merged