관심상품 기능
f-lab-edu/FKREAM pull request #53
Opened 2023-04-23 16:07 UTC by Chanhook

- Mapper 기능 및 테스트
- Service 기능 및 테스트
- Controller 기능 및 테스트

참고: #41

2023-04-25 20:14 UTC, f-lab-jason requested changes

2023-04-25 20:14 UTC, f-lab-jason commented on src/main/java/com/flab/fkream/interestedItem/InterestedItemController.java
> +    @GetMapping("/interested-items/users/{id}")
세션에서 말씀드렸던것처럼 `/interested-items` GET mapping으로 하고 userId는 세션에서 가져오면 좋겠어요

2023-04-25 20:14 UTC, f-lab-jason commented on src/main/java/com/flab/fkream/interestedItem/InterestedItemController.java
>  public class InterestedItemController {
여기 로직들도 유저가 권한체크가 필요할 것 같은데 확인부탁드려요.

2023-04-25 20:14 UTC, f-lab-jason commented on src/main/resources/mybatis/mapper/InterestedItem.xml
> +    </delete>
이런식으로 삭제하면 모든 유저들의 관심상품에서 id에 해당하는 데이터가 지워지는거아닌가요?

2023-04-27 16:07 UTC, Chanhook commented on src/main/java/com/flab/fkream/interestedItem/InterestedItemController.java
> +    @GetMapping("/interested-items/users/{id}")
수정하였습니다.

2023-04-27 16:17 UTC, Chanhook commented on src/main/resources/mybatis/mapper/InterestedItem.xml
> +    </delete>
네 맞습니다. 유저 아이디와 itemSizePriceId 로 조건을 걸어서 삭제하는 것이 맞는 것 같습니다

2023-04-28 04:38 UTC, Chanhook commented on src/main/java/com/flab/fkream/interestedItem/InterestedItemController.java
>  public class InterestedItemController {
권한체크 적용했습니다.

2023-04-28 04:55 UTC, merged