Feature/deal
f-lab-edu/FKREAM pull request #55
Opened 2023-04-24 12:16 UTC by bfinecpa

시세 기능
구매 내역 기능
판매 내역 기능

2023-04-25 20:46 UTC, f-lab-jason requested changes

2023-04-25 20:46 UTC, f-lab-jason commented on src/main/java/com/flab/fkream/deal/Deal.java
> +    public void setTradingDayToNow() { tradingDay = LocalDate.now();}
nit: formatter는 돌려보셨나요?

2023-04-25 20:46 UTC, f-lab-jason commented on src/main/java/com/flab/fkream/deal/DealController.java
> +        @RequestParam(required = false) String period,
period는 단순 string보단 enum형태가 더 좋을 것 같은데 어떻게 생각하시나요?

2023-04-25 20:46 UTC, f-lab-jason commented on src/main/java/com/flab/fkream/deal/DealService.java
> +        LocalDate ago = getPeriod(period);
ago보다 의미있는 변수명이면 좋겠습니다. (ago는 명사도 아니구요) 쿼리를 봐선 trading_day의 시작일같은데 그럼 minTradingDay나 fromTradingDay같은게 더 나을 것 같아요

2023-04-25 20:46 UTC, f-lab-jason commented on src/main/java/com/flab/fkream/deal/DealService.java
> +        KindOfDeal kindOfDeal) {
nit: kindOfDeal보다는 dealType같은게 더 나아보이는데..이걸 고치려면 db도 고쳐야하니 이건 어떻게 할지 주덕님이 정하셔도 될 것 같습니다.

2023-04-25 20:46 UTC, f-lab-jason commented on src/main/resources/mybatis/mapper/DealMapper.xml
> +  <select id="findPurchaseHistories" resultType="com.flab.fkream.deal.DealHistoryDto">
쿼리 사이엔 공백으로 띄워주세요. (formatter에서 이건 안잡아주나요?)

2023-04-25 20:46 UTC, f-lab-jason commented on src/main/java/com/flab/fkream/deal/DealService.java
> +        return null;
1. 다른 커멘트에서도 말씀드린것처럼 enum 타입을 입력으로 받으면 좋겠습니다
2. 입력으로 받는 string으로 comparing 할거면 항상 trim과 ignore case를 같이 해주시면 좋습니다.

2023-04-27 13:41 UTC, bfinecpa commented on src/main/java/com/flab/fkream/deal/DealController.java
> +        @RequestParam(required = false) String period,
> period는 단순 string보단 enum형태가 더 좋을 것 같은데 어떻게 생각하시나요?

네 enum으로 고치겠습니다.

2023-04-27 13:49 UTC, bfinecpa commented on src/main/java/com/flab/fkream/deal/DealService.java
> +        LocalDate ago = getPeriod(period);
네 fromTradingDay으로 변경하겠습니다.

2023-04-27 13:52 UTC, bfinecpa commented on src/main/resources/mybatis/mapper/DealMapper.xml
> +  <select id="findPurchaseHistories" resultType="com.flab.fkream.deal.DealHistoryDto">
> 쿼리 사이엔 공백으로 띄워주세요. (formatter에서 이건 안잡아주나요?)

formatter가 안잡아줍니다.
쿼리 사이에 공백으로 뛰우겠습니다.

2023-04-27 13:52 UTC, bfinecpa commented on src/main/java/com/flab/fkream/deal/DealService.java
> +        return null;
넵 알겠습니다.

2023-04-27 14:31 UTC, merged