보유 상품 기능
f-lab-edu/FKREAM pull request #56
Opened 2023-04-25 00:27 UTC by Chanhook

보유 상품 기능 구현했습니다.

세션을 이용하여 해당 유저가 아닌 경우에 해당 보유 상품 엔티티에 접근 할 수 없도록 설정했습니다.

2023-04-25 20:59 UTC, f-lab-jason requested changes

2023-04-25 20:59 UTC, f-lab-jason commented on src/main/java/com/flab/fkream/error/exception/ForbiddenException.java
> +        super("Access Denied");
주덕님과 상의해서 에러 메세지는 모두 한글로 하거나 영어로 하는걸로 통일해주세요. 두분이서 서로 다른 언어를 쓰시는거같네요.

2023-04-25 20:59 UTC, f-lab-jason commented on src/main/java/com/flab/fkream/ownedItems/OwnedItem.java
> +    @Min(value = 30000, message = "Purchase price must be at least 30,000")
미니멈이 왜 30,000이예요?

2023-04-25 20:59 UTC, f-lab-jason commented on src/main/java/com/flab/fkream/ownedItems/OwnedItemController.java
> +        }
세션에서 말씀드렸던것처럼 이 부분을 추상화할 수 있는 util class나 annotation 같은걸 고민해보면 좋겠어요. 여러군데서 쓰일테니 한군데서 처리 가능하면 좋을 것 같은데, 이 PR에서 업데이트할 필요는 없을 것 같구요.

2023-04-25 20:59 UTC, f-lab-jason commented on src/main/java/com/flab/fkream/ownedItems/OwnedItemController.java
> +    @GetMapping("/owned-items/users/{id}")
세션에서 말씀드린것처럼 id는 파라미터로 받지말고 세션에 있는걸 꺼내 쓰시면 좋겠습니다.

2023-04-25 20:59 UTC, f-lab-jason commented on src/main/java/com/flab/fkream/ownedItems/OwnedItemController.java
>  public class OwnedItemController {
nit: URL도 그렇고 controller도 그렇고 `/my-items`같은게 더 직관적이지 않을까요?

2023-04-25 20:59 UTC, f-lab-jason commented on src/main/java/com/flab/fkream/ownedItems/OwnedItemService.java
>  public class OwnedItemService {
여기 로직이 전체적으로 굉장히 불완전해 보이는데..
1. save: 아무 userId나 itemId를 `OwnedItem`의 입력에 넣어서 보내면 그대로 저장되지 않나요?
2. findOne: 아무 ownedItemId를 넣으면 다른 사용자의 데이터도 볼 수 있는거 아닌가요?
3. update: 아무 itemSizePriceId를 넣으면 실제 item size price 데이터가 있는지 여부와 관계없이 그냥 db에 들어가지 않나요?
4. delete: 아무 ownedItemId를 넣으면 다른 사용자의 데이터도 지울 수 있지 않나요?

확인부탁드려요.

2023-04-27 04:37 UTC, Chanhook commented on src/main/java/com/flab/fkream/ownedItems/OwnedItemController.java
> +    @GetMapping("/owned-items/users/{id}")
세션에서 바로 받게 하겠습니다!

2023-04-27 04:37 UTC, Chanhook commented on src/main/java/com/flab/fkream/error/exception/ForbiddenException.java
> +        super("Access Denied");
한글로 통일하겠습니다.

2023-04-27 04:44 UTC, Chanhook commented on src/main/java/com/flab/fkream/ownedItems/OwnedItem.java
> +    @Min(value = 30000, message = "Purchase price must be at least 30,000")
실제 KREAM 서비스의 경우 보유 상품 기능에서 최소 30000원부터 등록이 가능하게 되어있습니다. 그 이유는 알 수 없으나,  발매가가 3만 원 이하인 경우의 상품에 대해서도 무조건 3만 원 이상부터 적게 되어있어 일단 그대로 진행을 하였습니다.

2023-04-28 05:08 UTC, bfinecpa approved these changes

2023-05-12 04:45 UTC, merged